/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package metodosnumericos;
import java.math.*;

/**
 *
 * @author Alejandro
 */
public class InterpolacionLagrange extends javax.swing.JFrame {

    /**
     * Creates new form InterpolacionLagrange
     */
    Double valorx; // es el valor del view
    String cadax; // el valor de x0 x 1 xn
    String cadaxcadena[]; //cadena que almacena los valores de x
    String cadenafx []; //cadena que almacena los valores de fx
    String funcionevaluar; // función a calcular
    int dimension=1;
    int contador=0;
      
    public InterpolacionLagrange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtvalorfx = new javax.swing.JTextField();
        jtvalorx = new javax.swing.JTextField();
        jtcadax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbInterpolarL = new javax.swing.JButton();
        jtDimension = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jlresultadofx = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlResultadofinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtvalorfx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtvalorfx.setNextFocusableComponent(jtvalorx);
        jtvalorfx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtvalorfxActionPerformed(evt);
            }
        });
        jtvalorfx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtvalorfxFocusLost(evt);
            }
        });

        jtvalorx.setNextFocusableComponent(jtDimension);
        jtvalorx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtvalorxFocusLost(evt);
            }
        });

        jtcadax.setNextFocusableComponent(jButton1);
        jtcadax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtcadaxFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Interpoalación de Lagrange");

        jLabel2.setText("Función f(x):");

        jLabel3.setText("Valor de X:");

        jLabel4.setText("Valor de X");

        jLabel5.setText("0");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbInterpolarL.setText("Calcular Interpolación");
        jbInterpolarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInterpolarLActionPerformed(evt);
            }
        });

        jtDimension.setNextFocusableComponent(jtcadax);
        jtDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDimensionActionPerformed(evt);
            }
        });
        jtDimension.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDimensionFocusLost(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nº", "X", "f(x)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setText("Dimensión");

        jLabel7.setText("Resultado F(x)");

        jLabel8.setText("Resultado Interpolación de Lagrange:");

        jlResultadofinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtvalorfx, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtvalorx, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                            .addComponent(jtDimension)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jbInterpolarL))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtcadax, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlresultadofx, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jlResultadofinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtvalorfx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtvalorx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jtcadax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jlresultadofx, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jbInterpolarL)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlResultadofinal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // TODO add your handling code here:
        
        //String cadaxcadena[]; //cadena que almacena los valores de x
  //  String cadenafx []; //cadena que almacena los valores de fx
       
        //Calculo de la función lo muestra en un label 
        jLabel5.setText(String.valueOf(contador));
      funcion f =new funcion();         
     String Resultadofx= f.evaluar(funcionevaluar,cadax);
        jlresultadofx.setText(Resultadofx);
        
        if (contador<=dimension){
           this.cadaxcadena[contador]= cadax;
            this.cadenafx[contador]=Resultadofx;
             
           this.jTable2.setValueAt(contador, contador, 0);
             this.jTable2.setValueAt(this.cadaxcadena[contador], contador, 1);
             this.jTable2.setValueAt(this.cadenafx[contador],contador   ,2);
             
             contador++;
            
        } else {
             jButton1.setEnabled(false);
        }
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calculodefx(){
        //String valorx; // es el valor del view
       int i=0, j=0;
       this.valorx=Double.parseDouble(jtvalorx.getText()); 
       double dividendo=1, divisor=1,resultado=0, contenidoX=0,contenidoxi=0, division=0, contenidoFx=0;
      
        for (i=0; i<=dimension; i++){
            //contenido de la funcion en i
             contenidoFx=Double.parseDouble(cadenafx[i]);
             contenidoxi=Double.parseDouble(cadaxcadena[i]);
            for (j=0; j<=dimension; j++ ){
                if (j!=i){
                    //contenido de la cadena x evaluado enj
                    contenidoX=Double.parseDouble(cadaxcadena[j]);
                    
                   
                    dividendo= (dividendo*( valorx-contenidoX));
                    divisor= (divisor*(contenidoxi-contenidoX));
                       
                        }
               }
              division=dividendo/divisor;
                    if (Double.isNaN(division)) {
                        division=0;
                  
                     }
                    resultado= (resultado+(division*contenidoFx));
            dividendo=1;
            divisor=1;
          
            
        }
        this.jlResultadofinal.setText(String.valueOf(resultado));
        
    }
    private void jtvalorfxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtvalorfxFocusLost
        // TODO add your handling code here:
             funcionevaluar= jtvalorfx.getText();
    }//GEN-LAST:event_jtvalorfxFocusLost

    private void jtvalorfxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtvalorfxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtvalorfxActionPerformed

    private void jtvalorxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtvalorxFocusLost
        // TODO add your handling code here:
         //valorx= djtvalorx.getText();
    }//GEN-LAST:event_jtvalorxFocusLost

    private void jtcadaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtcadaxFocusLost
        // TODO add your handling code here:
        cadax=jtcadax.getText();
    }//GEN-LAST:event_jtcadaxFocusLost

    private void jtDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDimensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDimensionActionPerformed

    private void jtDimensionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDimensionFocusLost
        // TODO add your handling code here:
        this.dimension=Integer.parseInt(jtDimension.getText());
         cadaxcadena=new String [dimension+1]; //cadena que almacena los valores de x
            cadenafx= new String[dimension+1];
    }//GEN-LAST:event_jtDimensionFocusLost

    private void jbInterpolarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInterpolarLActionPerformed
        // TODO add your handling code here:
        calculodefx();
    }//GEN-LAST:event_jbInterpolarLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterpolacionLagrange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbInterpolarL;
    private javax.swing.JLabel jlResultadofinal;
    private javax.swing.JLabel jlresultadofx;
    private javax.swing.JTextField jtDimension;
    private javax.swing.JTextField jtcadax;
    private javax.swing.JTextField jtvalorfx;
    private javax.swing.JTextField jtvalorx;
    // End of variables declaration//GEN-END:variables
}
