/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package metodosnumericos;

/**
 *
 * @author Alejandro
 */
public class NewtonRaphsonModificado extends javax.swing.JFrame {

    /**
     * Creates new form NewtonRaphsonModificado
     */
    
   
    String strValorX;
    String strValorX1;// el valor de x0 x 1 xn
    Double iEa;
    Double oEa=Double.NaN;
    String strResFx; 
    String strResFx1; 
    String strResFx2;
    String strfuncionFx; // función a calcular
    String strfuncionFx1;
    String strfuncionFx2;
funcion f =new funcion();
      
    public NewtonRaphsonModificado() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlresultadofx = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlResultadofinal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtErrorAproximado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtFx = new javax.swing.JTextField();
        jtX0 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtFx1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtFx2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlResultadofinal1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Función f(x):");

        jlResultadofinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton1.setText("Calculo de Raíz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor de X");

        jtErrorAproximado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtErrorAproximadoFocusLost(evt);
            }
        });

        jLabel3.setText("|Ea|:");

        jtFx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtFx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFxActionPerformed(evt);
            }
        });
        jtFx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFxFocusLost(evt);
            }
        });

        jtX0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtX0FocusLost(evt);
            }
        });

        jLabel5.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Función f'(x):");

        jtFx1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtFx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFx1ActionPerformed(evt);
            }
        });
        jtFx1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFx1FocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Función f''(x):");

        jtFx2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtFx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFx2ActionPerformed(evt);
            }
        });
        jtFx2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFx2FocusLost(evt);
            }
        });

        jLabel6.setText("%");

        jLabel8.setText("Raíz");

        jLabel11.setText("Error Aproximado:");

        jlResultadofinal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Método de Newton-Raphson Modificado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jlresultadofx, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlResultadofinal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlResultadofinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtX0, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtErrorAproximado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(jtFx2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jtFx1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtFx, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtFx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtFx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtErrorAproximado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jtX0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlresultadofx, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlResultadofinal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jlResultadofinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //String cadaxcadena[]; //cadena que almacena los valores de x
        //  String cadenafx []; //cadena que almacena los valores de fx

        //Calculo de la función lo muestra en un label
        this.strfuncionFx=jtFx.getText();
        this.strfuncionFx1=jtFx1.getText();
        this.strfuncionFx2=jtFx2.getText();
        this.iEa=Double.parseDouble(jtErrorAproximado.getText());
        this.strValorX=this.jtX0.getText();
        
        do{
        this.strResFx= f.evaluar(this.strfuncionFx,this.strValorX);
        this.strResFx1= f.evaluar(this.strfuncionFx1,this.strValorX);
        this.strResFx2= f.evaluar(this.strfuncionFx2,this.strValorX);
        
        this.strValorX1 = calculoxn1(strValorX, strResFx,strResFx1,strResFx2);
        
        this.oEa= ErrorAproximado(strValorX,strValorX1);
        this.strValorX=this.strValorX1;    
        }while(oEa>=iEa);

        this.jlResultadofinal.setText(strValorX);
        this.jlResultadofinal1.setText(oEa.toString());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtErrorAproximadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtErrorAproximadoFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtErrorAproximadoFocusLost

    private void jtFxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFxActionPerformed

    private void jtFxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFxFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtFxFocusLost

    private void jtX0FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtX0FocusLost
        // TODO add your handling code here: De esta forma para que solo se cargue una vez
        this.strValorX=this.jtX0.getText();
        
    }//GEN-LAST:event_jtX0FocusLost

    private void jtFx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFx1ActionPerformed

    private void jtFx1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFx1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFx1FocusLost

    private void jtFx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFx2ActionPerformed

    private void jtFx2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFx2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFx2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphsonModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphsonModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphsonModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphsonModificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewtonRaphsonModificado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlResultadofinal;
    private javax.swing.JLabel jlResultadofinal1;
    private javax.swing.JLabel jlresultadofx;
    private javax.swing.JTextField jtErrorAproximado;
    private javax.swing.JTextField jtFx;
    private javax.swing.JTextField jtFx1;
    private javax.swing.JTextField jtFx2;
    private javax.swing.JTextField jtX0;
    // End of variables declaration//GEN-END:variables

 

    private String calculoxn1(String strValorX,String strResFx, String strResFx1, String strResFx2) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Double strValorX1= Double.parseDouble(strValorX);
        Double resFx= Double.parseDouble(strResFx);
        Double resFx1=Double.parseDouble(strResFx1);
        Double resFx2=Double.parseDouble(strResFx2);
        
        strValorX1= (strValorX1 -((resFx*resFx1)/((Math.pow(resFx1, 2)-(resFx*resFx2)))));
        
        return (strValorX1.toString());
        
        
    }

    private Double ErrorAproximado(String strValorX, String strValorX1) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Double pAct=Double.parseDouble(strValorX1);
        Double pAnt=Double.parseDouble(strValorX);
        Double EA=(((pAct-pAnt)/pAct)*100);
        EA=Math.abs(EA);
        return (EA);
    }
}
